// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import LikeButtonController from "./like_button_controller"
application.register("like-button", LikeButtonController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NutritionixController from "./nutritionix_controller"
application.register("nutritionix", NutritionixController)
